// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbyKSL6KtdHIJ6H_NJvxPs2ab0E9fSkEw',
    appId: '1:860518268482:web:2ceb9eb647b68961e277db',
    messagingSenderId: '860518268482',
    projectId: 'unicode-test-f484d',
    authDomain: 'unicode-test-f484d.firebaseapp.com',
    storageBucket: 'unicode-test-f484d.appspot.com',
    measurementId: 'G-9SV5FZZWS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DeiglD6hpU_QaDe2ElwLw4ZVIMTt1ds',
    appId: '1:860518268482:android:20dad20fc34ae3a5e277db',
    messagingSenderId: '860518268482',
    projectId: 'unicode-test-f484d',
    storageBucket: 'unicode-test-f484d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfBumlbirgTizvSuyQDdib52zuOTKdzvg',
    appId: '1:860518268482:ios:47a4fdc1a21e9644e277db',
    messagingSenderId: '860518268482',
    projectId: 'unicode-test-f484d',
    storageBucket: 'unicode-test-f484d.appspot.com',
    iosBundleId: 'com.example.unicodeTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfBumlbirgTizvSuyQDdib52zuOTKdzvg',
    appId: '1:860518268482:ios:47a4fdc1a21e9644e277db',
    messagingSenderId: '860518268482',
    projectId: 'unicode-test-f484d',
    storageBucket: 'unicode-test-f484d.appspot.com',
    iosBundleId: 'com.example.unicodeTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbyKSL6KtdHIJ6H_NJvxPs2ab0E9fSkEw',
    appId: '1:860518268482:web:23ad0c896ec1fa8be277db',
    messagingSenderId: '860518268482',
    projectId: 'unicode-test-f484d',
    authDomain: 'unicode-test-f484d.firebaseapp.com',
    storageBucket: 'unicode-test-f484d.appspot.com',
    measurementId: 'G-ZLWWW723P2',
  );
}
